#!/usr/bin/env bash
# One-time setup for a workshop participant. Run it from anywhere:
#
#     bash /shared/llmflux-workshop/workshop/setup_workshop.sh            # -> ~/llmflux-workshop
#     bash /shared/llmflux-workshop/workshop/setup_workshop.sh ~/my-dir   # somewhere else
#
# It copies the exercise files into your own directory and writes
# workshop.env, which you `source` to load the facilitator's settings.
# Safe to run again: it never overwrites files you've edited.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="${WORKSHOP_CONF:-$SRC/workshop.conf}"
DEST="${1:-$HOME/llmflux-workshop}"

if [[ ! -f "$CONF" ]]; then
    echo "Settings file not found: $CONF" >&2
    exit 1
fi
# shellcheck source=workshop.conf
source "$CONF"

unset_vars=()
for var in WORKSHOP_SYSTEM WORKSHOP_ACCOUNT WORKSHOP_RESERVATION WORKSHOP_PARTITION \
           WORKSHOP_MODEL WORKSHOP_DATASET WORKSHOP_TIME WORKSHOP_HF_HOME \
           WORKSHOP_CONTAINERS_DIR WORKSHOP_MODULE WORKSHOP_SAMPLE_RESULTS; do
    if [[ "${!var-CHANGE_ME}" == "CHANGE_ME" ]]; then
        unset_vars+=("$var")
    fi
done
if (( ${#unset_vars[@]} )); then
    echo "The workshop isn't configured yet (${unset_vars[*]} not set in $CONF)." >&2
    echo "Please let the facilitator know." >&2
    exit 1
fi
for var in WORKSHOP_ACCOUNT WORKSHOP_PARTITION WORKSHOP_MODEL WORKSHOP_DATASET WORKSHOP_TIME; do
    if [[ -z "${!var}" ]]; then
        echo "$var is empty in $CONF - it's required. Please let the facilitator know." >&2
        exit 1
    fi
done

# Settings that can't work together fail here, once, with a message that says
# what's wrong - not later as a Slurm error in front of every participant.
case "$WORKSHOP_SYSTEM" in
    delta)   [[ "$WORKSHOP_PARTITION" != ghx4* ]] \
                 || { echo "WORKSHOP_PARTITION=$WORKSHOP_PARTITION is a DeltaAI partition, but WORKSHOP_SYSTEM=delta in $CONF." >&2; exit 1; }
             [[ "$WORKSHOP_ACCOUNT" == *-delta-* ]] \
                 || echo "Warning: WORKSHOP_ACCOUNT=$WORKSHOP_ACCOUNT doesn't look like a Delta account (xxxx-delta-gpu)." >&2 ;;
    deltaai) [[ "$WORKSHOP_PARTITION" == ghx4* ]] \
                 || { echo "WORKSHOP_PARTITION=$WORKSHOP_PARTITION is not a DeltaAI partition (ghx4), but WORKSHOP_SYSTEM=deltaai in $CONF." >&2; exit 1; }
             [[ "$WORKSHOP_ACCOUNT" == *-dtai-* ]] \
                 || echo "Warning: WORKSHOP_ACCOUNT=$WORKSHOP_ACCOUNT doesn't look like a DeltaAI account (xxxx-dtai-gh)." >&2 ;;
    *)       echo "WORKSHOP_SYSTEM must be \"delta\" or \"deltaai\" in $CONF (got \"$WORKSHOP_SYSTEM\")." >&2
             exit 1 ;;
esac
case "$WORKSHOP_DATASET" in
    general|genomics) ;;
    *) echo "WORKSHOP_DATASET must be \"general\" or \"genomics\" in $CONF (got \"$WORKSHOP_DATASET\")." >&2
       exit 1 ;;
esac

# Refuse to continue on the wrong cluster: a job submitted from Delta with
# DeltaAI's partition (or the reverse) fails with an error that's hard to
# decode on your first day. Matches login and compute node names, so this also
# works from an Open OnDemand Jupyter or VS Code session; unknown hosts pass.
check_system() {
    local host="${WORKSHOP_HOSTNAME:-$(hostname)}" wrong=""
    case "$WORKSHOP_SYSTEM" in
        delta)   [[ "$host" == gh-* || "$host" == gh[0-9]* || "$host" == dtai-* ]] && wrong=DeltaAI ;;
        deltaai) [[ "$host" == dt-* || "$host" == gpu[a-z][0-9]* || "$host" == cn[0-9]* ]] && wrong=Delta ;;
    esac
    if [[ -n "$wrong" ]]; then
        local right="Delta (login.delta.ncsa.illinois.edu)"
        [[ "$WORKSHOP_SYSTEM" == deltaai ]] && right="DeltaAI (dtai-login.delta.ncsa.illinois.edu)"
        echo "This workshop runs on $right, but you're logged in to $wrong ($host)." >&2
        echo "Log out, log in to the right system, and run this again." >&2
        exit 1
    fi
}
check_system

mkdir -p "$DEST/data" "$DEST/prompts" "$DEST/results"
DEST="$(cd "$DEST" && pwd)"

# Copy unless the participant already has the file - they may have edited it.
# (Not `cp -n`: newer coreutils print a deprecation warning for it.)
copy_new() {
    [[ -e "$2" ]] || cp "$1" "$2"
}
for f in make_prompts.py show_results.py submit.sh data/abstracts.csv data/genomics_abstracts.csv; do
    copy_new "$SRC/$f" "$DEST/$f"
done

if [[ -n "$WORKSHOP_SAMPLE_RESULTS" && -d "$WORKSHOP_SAMPLE_RESULTS" ]]; then
    mkdir -p "$DEST/sample_results"
    for f in "$WORKSHOP_SAMPLE_RESULTS"/*.json; do
        if [[ -e "$f" ]]; then copy_new "$f" "$DEST/sample_results/$(basename "$f")"; fi
    done
fi

# Regenerated every run so a facilitator fix to workshop.conf reaches everyone
# who re-runs setup. %q quotes each value so spaces etc. survive `source`.
{
    echo "# Generated by setup_workshop.sh - load with:  source $DEST/workshop.env"
    echo "# Re-run setup_workshop.sh to regenerate; edits here are overwritten."
    printf 'export WORKSHOP_SYSTEM=%q\n' "$WORKSHOP_SYSTEM"
    printf 'export WORKSHOP_ACCOUNT=%q\n' "$WORKSHOP_ACCOUNT"
    printf 'export WORKSHOP_RESERVATION=%q\n' "$WORKSHOP_RESERVATION"
    printf 'export WORKSHOP_PARTITION=%q\n' "$WORKSHOP_PARTITION"
    printf 'export WORKSHOP_MODEL=%q\n' "$WORKSHOP_MODEL"
    printf 'export WORKSHOP_DATASET=%q\n' "$WORKSHOP_DATASET"
    printf 'export WORKSHOP_TIME=%q\n' "$WORKSHOP_TIME"
    # Everything LLMFlux creates (job scripts, logs, caches) goes under here.
    printf 'export LLMFLUX_WORKSPACE=%q\n' "$DEST"
    if [[ -n "$WORKSHOP_HF_HOME" ]]; then
        printf 'export HF_HOME=%q\n' "$WORKSHOP_HF_HOME"
    fi
    if [[ -n "$WORKSHOP_MODULE" ]]; then
        # Only load the module if llmflux isn't already available, so sourcing
        # this file twice is harmless.
        printf 'if ! command -v llmflux >/dev/null 2>&1; then\n'
        printf '    module load %q && conda activate base\n' "$WORKSHOP_MODULE"
        printf 'fi\n'
    fi
    # After the module load, so it overrides whatever the module file sets.
    if [[ -n "$WORKSHOP_CONTAINERS_DIR" ]]; then
        printf 'export LLMFLUX_CONTAINERS_DIR=%q\n' "$WORKSHOP_CONTAINERS_DIR"
    fi
    printf 'cd %q\n' "$DEST"
} > "$DEST/workshop.env"

cat <<EOF

Workshop files are ready in: $DEST

Next, load the settings (do this again every time you log in):

    source $DEST/workshop.env

Then continue with Part 3 of the workshop guide.
EOF
